import type { LanguageId } from './types'

export const copy = {
  ja: {
    appName: 'Name Nature',
    navHome: 'ホーム',
    navAnalyze: '分析',
    navGuide: '図鑑',
    heroTitle: '最初にカテゴリを絞ってから、参考画像で候補を確認する。',
    heroLead:
      'いきなり自然物すべてを当てにいかず、花や鳥などの前提を先に与えることで、候補の質と説明の納得感を上げる試作です。',
    homeActionAnalyze: '分析を始める',
    homeActionGuide: '図鑑を見る',
    homeFeatureLabel: 'できること',
    homeFeatureCards: [
      {
        title: 'カテゴリ先行で絞り込む',
        body: '花、キノコ、鳥、昆虫の前提を先に与えてから判定するので、候補が比較しやすくなります。',
      },
      {
        title: '参考画像で最終確認する',
        body: '推論結果をそのまま確定せず、参考画像と分類を見ながら一番近いものを自分で選べます。',
      },
      {
        title: '自分だけの図鑑として残す',
        body: '承認した候補も、該当なしだった観察も保存して、分類メモと自由記述を育てられます。',
      },
    ],
    homeCollectionTitle: 'フィールドログ',
    homeCollectionCopy: '今ある記録を起点に、次に何をするかをすぐ選べるようにします。',
    homeCollectionTotal: '保存件数',
    homeCollectionApproved: '承認済み',
    homeCollectionRejected: '該当なし',
    homeRecentTitle: '最近の観察',
    homeRecentEmpty: 'まだ観察記録はありません。まずは1枚分析してみてください。',
    homeReadyTitle: 'すぐ再開できます',
    homeReadyCopy: '途中まで進めた分析や図鑑の確認へ、ここから直接移動できます。',
    homeAnalysisCardTitle: '分析フローへ',
    homeAnalysisCardBody: 'カテゴリ選択、画像アップロード、候補確認までを1ページで進めます。',
    homeGuideCardTitle: '図鑑ページへ',
    homeGuideCardBody: '保存済みの観察を一覧し、分類やメモ、豆知識チャットを見返せます。',
    analysisPageLabel: 'Analysis',
    analysisPageTitle: 'カテゴリを決めてから候補を照合する',
    analysisPageLead: 'カテゴリの選択・写真の読み込み・候補の確認を、このページに順に並べています。',
    analysisChoicePrompt: '何と出会った？',
    analysisChooseLead: '見分けたい対象のカテゴリを選びます。',
    analysisUploadLead: '選んだカテゴリの前提で写真を1枚読み込み、解析を開始します。',
    analysisResultLead: '推論結果の候補を比較し、必要なら図鑑に保存します。',
    analysisCurrentCategory: '選択中のカテゴリ',
    analysisChangeCategory: 'カテゴリを選び直す',
    analysisChangePhoto: '別の写真を選ぶ',
    analysisOpenGuide: '図鑑を開く',
    guidePageLabel: 'Field Guide',
    guidePageTitle: '保存した観察をあとで育てる',
    guidePageLead: '図鑑ページでは、承認結果、分類メモ、自由メモ、豆知識チャットをまとめて扱います。',
    steps: ['カテゴリ選択', '画像アップロード', '候補の了承確認'],
    languageLabel: 'Language',
    languages: { ja: '日本語', en: 'English' },
    categories: {
      flower: {
        name: '花',
        description: 'Flowering Plants に絞り、花の候補を優先して照合します。',
      },
      fungus: {
        name: 'キノコ',
        description: 'Fungi に絞り、キノコや菌類の候補を優先して照合します。',
      },
      bird: {
        name: '鳥',
        description: 'くちばし、羽色、体格比を使って近い種を挙げます。',
      },
      insect: {
        name: '昆虫',
        description: '羽の模様、脚の本数、体節の特徴を中心に判定します。',
      },
    },
    currentContext: '現在の前提:',
    step1: '何を解析したいかを先に選ぶ',
    step2: '写真を読み込んで解析を開始',
    step3: '候補を例画像つきで提示し、ユーザーに確認してもらう',
    step3Copy:
      'iNaturalist の推論結果から上位候補を取り出し、参考画像と分類情報を並べて了承を取ります。',
    selectPhoto: '自然の写真を選択',
    selectPhotoHint: '画像をドラッグ＆ドロップ、またはインポート',
    preview: '画像プレビュー',
    previewHint: '撮影した写真を読み込むと、ここに確認用プレビューを表示します。',
    analyzeReady: '画像を選ぶと解析できます',
    analyzing: 'iNaturalist へ問い合わせ中',
    analyzeAs: (categoryName: string) => `${categoryName}として候補を出す`,
    loadingBanner: '画像を送信し、実際の推論結果を取得しています。数秒かかることがあります。',
    idleTitle: 'まだ解析は始まっていません',
    idleCopy: 'カテゴリを選び、写真を1枚読み込むと候補比較エリアが有効になります。',
    readyTitle: (categoryName: string) => `${categoryName}として解析する準備ができています`,
    readyCopy: '解析を始めると、iNaturalist の上位候補と代表画像、分類情報を並べて表示します。',
    emptyTitle: '候補が見つかりませんでした',
    emptyCopy: 'カテゴリが厳しすぎる可能性があります。別カテゴリでも試してください。',
    noImage: '参考画像なし',
    confidence: (value: number) => `${value}%一致見込み`,
    detailsLink: 'iNaturalistで詳細を見る',
    confirmed: 'これだ！',
    confirm: 'これだ！',
    analyzeAgain: '別の解析を行う',
    goHome: 'ホームに戻る',
    confirmedTitle: () => 'あなたに、よりよい自然の出会いを',
    confirmedCopy:
      '次の段階では、この候補に対して追加質問を出したり、類似候補との差分比較へ進めたりできます。',
    awaiting: 'Awaiting Approval',
    awaitingTitle: '候補を見比べて、一番近い参考画像を選んでください',
    awaitingCopy: 'ここで了承を取ることで、誤った候補に対して深掘りする無駄を減らせます。',
    noneOfThese: 'どれも違いそう…',
    unknown: '不明',
    rejectedTitle: 'すみません…私に新たな発見をありがとう！',
    rejectedCopy: '今回は候補を承認せず、自分の図鑑にメモとして残します。',
    savedGuide: '図鑑に保存しました！',
    deletedGuide: '図鑑の記録を削除しました。',
    guideTitle: '図鑑',
    guideCopy: '自分が追加した観察メモを残し、承認内容や「該当なし」を後から見返せます。',
    guideEmpty: 'まだ図鑑の記録はありません。候補を承認するか、該当なしを選ぶとここへ追加されます。',
    guideConfirmed: '承認済み',
    guideRejected: '該当なし',
    guideOpenEditor: '内容を編集',
    guideEdit: '編集',
    guideEditDone: '完了',
    guideSelectAll: 'すべて選択',
    guideDeleteSelected: '選択を削除',
    guideDeleteSelectedConfirm: '選択した記録を削除します。削除後は復元できません。本当に削除しますか？',
    guideDelete: 'この記録を削除',
    editorTitle: '記録を編集',
    editorName: '表示名',
    editorNotes: 'メモ',
    editorPlaceholderName: '自分なりの名前をつける',
    editorPlaceholderNotes: '気づいた特徴や場所、季節などをメモする',
    editorSaved: 'この場で自動保存されます',
    taxonomyTitle: '分類',
    taxonomyFamily: '科',
    taxonomyOrder: '目',
    taxonomyClass: '綱',
    taxonomyPhylum: '門',
    taxonomyKingdom: '界',
    chatTitle: '豆知識チャット',
    chatPlaceholder: '花言葉は？ 由来は？ よく似た種類は？ など',
    chatSubmit: '送信する',
    chatLoading: '回答を生成しています',
    chatEmpty: 'この観察対象について知りたい豆知識を質問できます。',
    confirmRestoreTitle: '分類を復元',
    confirmRestoreMessage: '分類データを撮影時の初期状態に上書きします。現在の編集内容は失われます。よろしいですか？',
    confirmDeleteTitle: '記録を削除',
    confirmDeleteMessage: 'この記録を削除します。削除後は復元できません。本当に削除しますか？',
    confirmCancel: 'キャンセル',
    confirmOk: '実行する',
  },
  en: {
    appName: 'Name Nature',
    navHome: 'Home',
    navAnalyze: 'Analyze',
    navGuide: 'Field Guide',
    heroTitle: 'Constrain the category first, then confirm candidates with reference images.',
    heroLead:
      'Instead of classifying every kind of natural object at once, this prototype narrows the context up front so the candidates feel more plausible and easier to verify.',
    homeActionAnalyze: 'Start Analysis',
    homeActionGuide: 'Open Field Guide',
    homeFeatureLabel: 'What It Does',
    homeFeatureCards: [
      {
        title: 'Narrow the search first',
        body: 'Choose flower, mushroom, bird, or insect first so the candidate list stays easier to review.',
      },
      {
        title: 'Confirm with reference images',
        body: 'The app does not auto-commit too early. You compare representative images and confirm the closest match yourself.',
      },
      {
        title: 'Keep a personal field guide',
        body: 'Store approved matches and no-match observations alike, then keep taxonomy and your own notes together.',
      },
    ],
    homeCollectionTitle: 'Field Log',
    homeCollectionCopy: 'Use the saved observations as a quick launch point for whatever you want to do next.',
    homeCollectionTotal: 'Saved',
    homeCollectionApproved: 'Approved',
    homeCollectionRejected: 'No match',
    homeRecentTitle: 'Recent Observation',
    homeRecentEmpty: 'No saved observations yet. Start with a single photo analysis.',
    homeReadyTitle: 'Resume from here',
    homeReadyCopy: 'Jump directly back into analysis or review your saved guide from the home page.',
    homeAnalysisCardTitle: 'Go to Analysis',
    homeAnalysisCardBody: 'Choose a category, upload a photo, and compare the resulting candidates on one page.',
    homeGuideCardTitle: 'Go to Field Guide',
    homeGuideCardBody: 'Review saved observations, taxonomy notes, freeform notes, and trivia chat in one place.',
    analysisPageLabel: 'Analysis',
    analysisPageTitle: 'Choose context first, then compare the candidates',
    analysisPageLead: 'Category, photo upload, and candidate review are listed in order on this page.',
    analysisChoicePrompt: 'What did you encounter?',
    analysisChooseLead: 'Pick the category that matches what you want to identify.',
    analysisUploadLead: 'Upload one photo under that category, then start inference.',
    analysisResultLead: 'Compare the suggested candidates and save to the field guide when ready.',
    analysisCurrentCategory: 'Selected category',
    analysisChangeCategory: 'Choose another category',
    analysisChangePhoto: 'Choose another photo',
    analysisOpenGuide: 'Open field guide',
    guidePageLabel: 'Field Guide',
    guidePageTitle: 'Grow your saved observations over time',
    guidePageLead: 'The field guide page keeps approvals, taxonomy, editable notes, and trivia chat together.',
    steps: ['Choose category', 'Upload image', 'Confirm candidate'],
    languageLabel: 'Language',
    languages: { ja: 'Japanese', en: 'English' },
    categories: {
      flower: {
        name: 'Flower',
        description: 'Restrict to flowering plants and prioritize flower-like candidates.',
      },
      fungus: {
        name: 'Mushroom',
        description: 'Restrict to fungi and prioritize mushrooms and fungus-like candidates.',
      },
      bird: {
        name: 'Bird',
        description: 'Use beak shape, plumage, and body proportions to narrow the candidates.',
      },
      insect: {
        name: 'Insect',
        description: 'Use wing patterns, leg count, and body segmentation to narrow the candidates.',
      },
    },
    currentContext: 'Current context:',
    step1: 'Choose what you want to analyze first',
    step2: 'Upload a photo and start analysis',
    step3: 'Show reference-backed candidates and let the user confirm them',
    step3Copy:
      'The app takes the top iNaturalist candidates, shows reference imagery and classification details, and asks the user to confirm the closest match.',
    selectPhoto: 'Choose a nature photo',
    selectPhotoHint: 'Designed for jpg / png / webp. The prototype currently handles one image at a time.',
    preview: 'Image preview',
    previewHint: 'Once you upload a photo, its preview appears here for confirmation.',
    analyzeReady: 'Choose an image to enable analysis',
    analyzing: 'Querying iNaturalist',
    analyzeAs: (categoryName: string) => `Analyze as ${categoryName}`,
    loadingBanner: 'Uploading the image and waiting for live inference results. This can take a few seconds.',
    idleTitle: 'Analysis has not started yet',
    idleCopy: 'Choose a category and upload a single image to activate the candidate comparison area.',
    readyTitle: (categoryName: string) => `Ready to analyze as ${categoryName}`,
    readyCopy: 'Once analysis starts, the app shows top iNaturalist candidates with representative images and taxonomic details.',
    emptyTitle: 'No reliable candidates were found',
    emptyCopy: 'The selected category may be too restrictive. Try a different category or another photo.',
    noImage: 'No reference image',
    confidence: (value: number) => `${value}% match estimate`,
    detailsLink: 'Open this candidate on iNaturalist',
    confirmed: 'This is it!',
    confirm: 'This is it!',
    analyzeAgain: 'Start another analysis',
    goHome: 'Back to home',
    confirmedTitle: () => 'To better encounters with nature',
    confirmedCopy:
      'The next step can ask follow-up questions or compare the selected candidate against similar alternatives.',
    awaiting: 'Awaiting Approval',
    awaitingTitle: 'Compare the candidates and choose the closest reference image',
    awaitingCopy: 'This approval step prevents the app from overcommitting to the wrong candidate too early.',
    noneOfThese: 'None of these look right',
    unknown: 'Unknown',
    rejectedTitle: 'Sorry about that... Thank you for the new discovery!',
    rejectedCopy: 'These candidates were not approved. The observation will still be stored in your field guide.',
    savedGuide: 'Saved to your field guide!',
    deletedGuide: 'The field guide entry was deleted.',
    guideTitle: 'My Field Guide',
    guideCopy: 'Keep a personal record of what you added, what you approved, and which observations had no convincing match.',
    guideEmpty: 'No field guide entries yet. Approve a candidate or choose no good match to add one here.',
    guideConfirmed: 'Approved',
    guideRejected: 'No match',
    guideOpenEditor: 'Edit entry',
    guideEdit: 'Edit',
    guideEditDone: 'Done',
    guideSelectAll: 'Select All',
    guideDeleteSelected: 'Delete Selected',
    guideDeleteSelectedConfirm: 'Delete selected entries permanently. This cannot be undone. Are you sure?',
    guideDelete: 'Delete this entry',
    editorTitle: 'Edit entry',
    editorName: 'Display name',
    editorNotes: 'Notes',
    editorPlaceholderName: 'Give this observation your own label',
    editorPlaceholderNotes: 'Add the details you want to remember later',
    editorSaved: 'Changes are saved automatically here',
    taxonomyTitle: 'Taxonomy',
    taxonomyFamily: 'Family',
    taxonomyOrder: 'Order',
    taxonomyClass: 'Class',
    taxonomyPhylum: 'Phylum',
    taxonomyKingdom: 'Kingdom',
    chatTitle: 'Trivia Chat',
    chatPlaceholder: 'For example: what is it known for? any symbolism?',
    chatSubmit: 'Send',
    chatLoading: 'Generating an answer',
    chatEmpty: 'Ask for trivia or extra background about this saved observation.',
    confirmRestoreTitle: 'Restore Taxonomy',
    confirmRestoreMessage: 'This will overwrite the taxonomy data with the original state from when the photo was taken. Current edits will be lost. Continue?',
    confirmDeleteTitle: 'Delete Entry',
    confirmDeleteMessage: 'This entry will be deleted permanently and cannot be recovered. Are you sure you want to delete?',
    confirmCancel: 'Cancel',
    confirmOk: 'Confirm',
  },
} as const

export type UiText = (typeof copy)[LanguageId]
